version: '3'
services:
  nginx:
    container_name: phal-test-nginx
    image: nginx:mainline-alpine
    restart: always
    ports:
      - '8000:80'
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
      - ./:/usr/src/app
    networks:
      - lemp-stack
    depends_on:
      - 'phalcon'
  phalcon:
    container_name: phal-test-fpm
    build: .
    restart: always
    volumes:
      - ./:/usr/src/app
    links:
      - 'redis:redis'
      - 'db:mariadb'
    networks:
      - lemp-stack
    depends_on:
      - 'db'
      - 'redis'
  db:
    container_name: phal-test-sql
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD: 123123
      - MYSQL_DATABASE: 'db'
    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d
  redis:
    container_name: phal-test-redis
    image: redis:6-alpine
    restart: always
    networks:
      - lemp-stack
networks:
  lemp-stack:
